<a href="https://colab.research.google.com/github/arnav177/Data-Science-Tools/blob/main/TensorFlow_arnav_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
s = tf.constant([2,0,-3,8,90])
print(s)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [4]:
s2 = tf.constant([
    [1,2,0],
    [3,1,2],
    [1,2,4]
])
print(s2)

tf.Tensor(
[[1 2 0]
 [3 1 2]
 [1 2 4]], shape=(3, 3), dtype=int32)


In [5]:
s_zero_d = tf.constant(4)
print(s_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [7]:
fill_tensor = tf.fill(
    [1,2,3], 5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5]
  [5 5 5]]], shape=(1, 2, 3), dtype=int32)


In [8]:
ones_tensor = tf.ones(
    [5,3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [21]:
tensor_three_d = tf.constant([[[4,2,3],
  [3,4,5],
  [2,1,1]],

 [[3,1,2],
  [8,9,0],
  [6,5,4]],

 [[1,4,5],
  [2,6,7],
  [3,2,5]],

 [[8,6,4],
  [2,6,7],
  [7,4,5]]])
print(tensor_three_d)

tf.Tensor(
[[[4 2 3]
  [3 4 5]
  [2 1 1]]

 [[3 1 2]
  [8 9 0]
  [6 5 4]]

 [[1 4 5]
  [2 6 7]
  [3 2 5]]

 [[8 6 4]
  [2 6 7]
  [7 4 5]]], shape=(4, 3, 3), dtype=int32)


In [9]:
random_tensor = tf.random.normal(
    [],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(0.025017655, shape=(), dtype=float32)


In [12]:
random_tensor = tf.random.normal(
    [3,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[ 1.1220391   0.68633497 -0.39775386]
 [-1.7640448  -0.36543977  0.9428229 ]
 [-0.44707006 -0.38195544  0.46301863]], shape=(3, 3), dtype=float32)


In [15]:
random_tensor = tf.random.uniform(
    [5,],
    maxval = 109,
    minval=0,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor([ 81.52685   41.8377    90.697395 102.18853   91.113235], shape=(5,), dtype=float32)


In [16]:
tf.range(12,1200)

<tf.Tensor: shape=(1188,), dtype=int32, numpy=array([  12,   13,   14, ..., 1197, 1198, 1199], dtype=int32)>

In [17]:
tensor_indexed = tf.constant([1,2,3,4,45,6])
print(tensor_indexed)
print(tensor_indexed[0:4])

tf.Tensor([ 1  2  3  4 45  6], shape=(6,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [19]:
tensor_two_d = tf.constant([[1,2,0],
                           [4,5,6],
                            [7,8,9],
                            [6,4,3]])
print(tensor_two_d[2,1:])

tf.Tensor([8 9], shape=(2,), dtype=int32)


In [20]:
tensor_two_d = tf.constant([[1,2,0],
                           [4,5,6],
                            [7,8,9],
                            [6,4,3]])
print(tensor_two_d[...,1])

tf.Tensor([2 5 8 4], shape=(4,), dtype=int32)


In [23]:
tensor_three_d = tf.constant([[[4,2,3],
  [3,4,5],
  [2,1,1]],

 [[3,1,2],
  [8,9,0],
  [6,5,4]],

 [[1,4,5],
  [2,6,7],
  [3,2,5]],

 [[8,6,4],
  [2,6,7],
  [7,4,5]]])
print(tensor_three_d[0, :, :])

tf.Tensor(
[[4 2 3]
 [3 4 5]
 [2 1 1]], shape=(3, 3), dtype=int32)


In [24]:
tf_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(tf_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [25]:
tf.abs(tf.constant(-0.7))

<tf.Tensor: shape=(), dtype=float32, numpy=0.7>

In [26]:
tf.sqrt(-2.25**2 + 4.87**2)

<tf.Tensor: shape=(), dtype=float32, numpy=4.319074>

In [1]:
import pandas as pd
import seaborn as sns

In [ ]:
map